import { Building, Floor, Room, Facility, Department, CampusNode, CampusEdge, Announcement, User } from '../types/campus';

export const INITIAL_BUILDINGS: Building[] = [
  {
    id: 'bld-gate',
    name: 'Campus Main Gate & Security Check',
    code: 'GATE',
    description: 'Main campus security entrance, visitor registration, security kiosk and transit hub',
    floorsCount: 1,
    color: '#0284c7', // sky
    x: 500,
    y: 770,
    width: 220,
    height: 60,
    entranceNodeId: 'node-main-gate',
  },
  {
    id: 'bld-parking',
    name: 'Student & Staff Parking Complex',
    code: 'PARK',
    description: 'Designated 2-wheeler and 4-wheeler parking with EV charging station',
    floorsCount: 1,
    color: '#475569',
    x: 230,
    y: 765,
    width: 180,
    height: 65,
    entranceNodeId: 'node-parking',
  },
  {
    id: 'bld-admin',
    name: 'Administrative Block',
    code: 'ADMIN',
    description: 'Principal Office, Exam Cell, Registrar, Accounts, Academic Dean and Board Room',
    floorsCount: 2,
    color: '#3b82f6', // blue
    x: 500,
    y: 600,
    width: 260,
    height: 140,
    entranceNodeId: 'node-admin-ent',
  },
  {
    id: 'bld-ece',
    name: 'ECE Block (Electronics & Communication)',
    code: 'ECE',
    description: 'ECE Department, VLSI & DSP Labs, Embedded IoT Lab, Seminar Hall and HOD Office',
    floorsCount: 2,
    color: '#8b5cf6', // purple
    x: 230,
    y: 520,
    width: 220,
    height: 140,
    entranceNodeId: 'node-ece-ent',
  },
  {
    id: 'bld-cse',
    name: 'CSE Block (Computer Science & Engineering)',
    code: 'CSE',
    description: 'AI & Cloud Computing Lab, Software Systems Suite, Robotics Hub, and CSE HOD Chamber',
    floorsCount: 2,
    color: '#06b6d4', // cyan
    x: 770,
    y: 520,
    width: 220,
    height: 140,
    entranceNodeId: 'node-cse-ent',
  },
  {
    id: 'bld-library',
    name: 'Central Library & Digital Knowledge Hub',
    code: 'LIB',
    description: 'Multi-tier lending library, digital study cubicles, IEEE journals and research archive',
    floorsCount: 2,
    color: '#10b981', // emerald
    x: 500,
    y: 335,
    width: 240,
    height: 130,
    entranceNodeId: 'node-lib-ent',
  },
  {
    id: 'bld-mech',
    name: 'Mechanical Engineering Block',
    code: 'MECH',
    description: 'CAD/CAM Simulation Center, Machine Shop, Fluid Mechanics and Design Studios',
    floorsCount: 2,
    color: '#f97316', // orange
    x: 230,
    y: 330,
    width: 220,
    height: 130,
    entranceNodeId: 'node-mech-ent',
  },
  {
    id: 'bld-auditorium',
    name: 'Grand Auditorium & Convocation Hall',
    code: 'AUD',
    description: 'Air-conditioned main auditorium with seating for 1200+ guests and cultural stage',
    floorsCount: 1,
    color: '#ec4899', // pink
    x: 770,
    y: 330,
    width: 220,
    height: 130,
    entranceNodeId: 'node-aud-ent',
  },
  {
    id: 'bld-canteen',
    name: 'Campus Canteen & Food Court',
    code: 'CAN',
    description: 'Hygienic vegetarian & multi-cuisine cafeteria, bakery, and fresh juice kiosk',
    floorsCount: 1,
    color: '#eab308', // amber
    x: 230,
    y: 130,
    width: 220,
    height: 120,
    entranceNodeId: 'node-canteen-ent',
  },
  {
    id: 'bld-amenities',
    name: 'Campus Health Center & Emergency Care',
    code: 'HEALTH',
    description: '24/7 First aid station, physician ward, pharmacy dispensary, and ambulance bay',
    floorsCount: 1,
    color: '#ef4444', // red
    x: 500,
    y: 130,
    width: 220,
    height: 120,
    entranceNodeId: 'node-health-ent',
  },
  {
    id: 'bld-hostel',
    name: 'Student Hostels & Residential Complex',
    code: 'HOSTEL',
    description: 'Hostel residences with recreational mess, gym, warden office and study rooms',
    floorsCount: 2,
    color: '#64748b', // slate
    x: 770,
    y: 130,
    width: 220,
    height: 120,
    entranceNodeId: 'node-hostel-ent',
  },
];

export const INITIAL_FLOORS: Floor[] = [
  // Admin
  { id: 'fl-admin-0', buildingId: 'bld-admin', floorNumber: 0, name: 'Ground Floor (Administrative)', elevation: 0 },
  { id: 'fl-admin-1', buildingId: 'bld-admin', floorNumber: 1, name: 'First Floor (Offices & Meeting)', elevation: 4 },
  // ECE
  { id: 'fl-ece-0', buildingId: 'bld-ece', floorNumber: 0, name: 'Ground Floor (Laboratories)', elevation: 0 },
  { id: 'fl-ece-1', buildingId: 'bld-ece', floorNumber: 1, name: 'First Floor (Classrooms & Seminar)', elevation: 4 },
  // CSE
  { id: 'fl-cse-0', buildingId: 'bld-cse', floorNumber: 0, name: 'Ground Floor (Computing Center)', elevation: 0 },
  { id: 'fl-cse-1', buildingId: 'bld-cse', floorNumber: 1, name: 'First Floor (AI & Robotics Hub)', elevation: 4 },
  // MECH
  { id: 'fl-mech-0', buildingId: 'bld-mech', floorNumber: 0, name: 'Ground Floor (Heavy Machinery & Labs)', elevation: 0 },
  { id: 'fl-mech-1', buildingId: 'bld-mech', floorNumber: 1, name: 'First Floor (Design Studios)', elevation: 4 },
  // Library
  { id: 'fl-lib-0', buildingId: 'bld-library', floorNumber: 0, name: 'Ground Floor (Lending & Stack)', elevation: 0 },
  { id: 'fl-lib-1', buildingId: 'bld-library', floorNumber: 1, name: 'First Floor (Digital Library & Reference)', elevation: 4 },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-ece',
    name: 'Electronics and Communication Engineering',
    code: 'ECE',
    buildingId: 'bld-ece',
    hodName: 'Dr. K. Senthil Nathan, Ph.D.',
    contactEmail: 'hod.ece@college.edu',
  },
  {
    id: 'dept-cse',
    name: 'Computer Science and Engineering',
    code: 'CSE',
    buildingId: 'bld-cse',
    hodName: 'Dr. R. Meenakshi, Ph.D.',
    contactEmail: 'hod.cse@college.edu',
  },
  {
    id: 'dept-mech',
    name: 'Mechanical Engineering',
    code: 'MECH',
    buildingId: 'bld-mech',
    hodName: 'Dr. A. Balaji, Ph.D.',
    contactEmail: 'hod.mech@college.edu',
  },
  {
    id: 'dept-admin',
    name: 'College Administration & Management',
    code: 'ADMIN',
    buildingId: 'bld-admin',
    hodName: 'Prof. Dr. V. Shanmugam, Principal',
    contactEmail: 'principal@college.edu',
  },
];

export const INITIAL_ROOMS: Room[] = [
  // Admin Block - Ground Floor
  {
    id: 'rm-principal',
    name: 'Principal Office',
    roomNumber: 'ADM-G01',
    buildingId: 'bld-admin',
    floorNumber: 0,
    departmentId: 'dept-admin',
    type: 'office',
    headFaculty: 'Dr. V. Shanmugam (Principal)',
    nodeRefId: 'node-admin-principal',
    tags: ['admin', 'principal', 'office', 'head', 'cabin'],
    aliases: ['principal office', 'principal room', 'head office', 'principal cabin', 'principal sir room', 'mudhalvar arai', 'principal enga irukku'],
  },
  {
    id: 'rm-exam-cell',
    name: 'Controller of Examinations (Exam Cell)',
    roomNumber: 'ADM-G02',
    buildingId: 'bld-admin',
    floorNumber: 0,
    departmentId: 'dept-admin',
    type: 'office',
    headFaculty: 'Prof. S. Murali (Controller)',
    nodeRefId: 'node-admin-exam',
    tags: ['exam', 'cell', 'hall tickets', 'controller', 'tests'],
    aliases: ['exam cell', 'examination cell', 'exam office', 'coe office', 'hall ticket office', 'paritchai arai', 'exam cell enga'],
  },
  {
    id: 'rm-accounts',
    name: 'Accounts & Fees Section',
    roomNumber: 'ADM-G03',
    buildingId: 'bld-admin',
    floorNumber: 0,
    departmentId: 'dept-admin',
    type: 'office',
    headFaculty: 'Mr. P. Ramanathan (Chief Finance Officer)',
    nodeRefId: 'node-admin-accounts',
    tags: ['fees', 'accounts', 'cashier', 'finance', 'scholarship'],
    aliases: ['accounts', 'accounts office', 'fees counter', 'cash counter', 'finance section', 'kattanam', 'fees kattanum'],
  },
  // Admin Block - 1st Floor
  {
    id: 'rm-board-room',
    name: 'Executive Board Room & Academic Council',
    roomNumber: 'ADM-101',
    buildingId: 'bld-admin',
    floorNumber: 1,
    departmentId: 'dept-admin',
    type: 'hall',
    capacity: 60,
    headFaculty: 'Registrar Office',
    nodeRefId: 'node-admin-boardroom',
    tags: ['meeting', 'board room', 'conference', 'council'],
    aliases: ['board room', 'conference hall', 'academic council room', 'meeting room'],
  },
  {
    id: 'rm-dean-office',
    name: 'Dean of Academic Affairs',
    roomNumber: 'ADM-102',
    buildingId: 'bld-admin',
    floorNumber: 1,
    departmentId: 'dept-admin',
    type: 'office',
    headFaculty: 'Dr. M. Chitra (Dean Academics)',
    nodeRefId: 'node-admin-dean',
    tags: ['dean', 'academics', 'curriculum', 'attendance'],
    aliases: ['dean office', 'dean academics', 'academic dean room'],
  },

  // ECE Block - Ground Floor
  {
    id: 'rm-ece-lab-1',
    name: 'ECE Lab 1 (VLSI & Digital Signal Processing)',
    roomNumber: 'ECE-G01',
    buildingId: 'bld-ece',
    floorNumber: 0,
    departmentId: 'dept-ece',
    type: 'lab',
    capacity: 65,
    headFaculty: 'Prof. T. Anand',
    nodeRefId: 'node-ece-lab1',
    tags: ['ece lab 1', 'vlsi', 'dsp', 'electronics', 'cadence'],
    aliases: ['ece lab 1', 'ece lab', 'vlsi lab', 'dsp lab', 'electronics lab 1', 'ece lab-ku', 'ece lab enga irukku'],
  },
  {
    id: 'rm-ece-lab-2',
    name: 'ECE Lab 2 (Embedded Systems & IoT Innovation)',
    roomNumber: 'ECE-G02',
    buildingId: 'bld-ece',
    floorNumber: 0,
    departmentId: 'dept-ece',
    type: 'lab',
    capacity: 60,
    headFaculty: 'Dr. G. Pavithra',
    nodeRefId: 'node-ece-lab2',
    tags: ['ece lab 2', 'iot', 'embedded', 'microcontroller', 'arduino'],
    aliases: ['ece lab 2', 'embedded lab', 'iot lab', 'microprocessor lab', 'ece second lab'],
  },
  // ECE Block - 1st Floor
  {
    id: 'rm-ece-dept-office',
    name: 'ECE Department Office & HOD Chamber',
    roomNumber: 'ECE-101',
    buildingId: 'bld-ece',
    floorNumber: 1,
    departmentId: 'dept-ece',
    type: 'office',
    headFaculty: 'Dr. K. Senthil Nathan (HOD)',
    nodeRefId: 'node-ece-dept-office',
    tags: ['ece hod', 'ece office', 'department', 'staff'],
    aliases: ['ece dept office', 'ece department office', 'ece hod room', 'ece hod office', 'ece hod cabin', 'ece staff room'],
  },
  {
    id: 'rm-seminar-hall',
    name: 'College Seminar Hall & Smart Audi-Conference',
    roomNumber: 'ECE-102',
    buildingId: 'bld-ece',
    floorNumber: 1,
    departmentId: 'dept-ece',
    type: 'hall',
    capacity: 250,
    headFaculty: 'Event Coordinator',
    nodeRefId: 'node-ece-seminar',
    tags: ['seminar', 'hall', 'presentation', 'guest lecture', 'symposium'],
    aliases: ['seminar hall', 'seminar room', 'ece seminar hall', 'conference hall', 'karutharangu', 'seminar hall enga irukku'],
  },

  // CSE Block
  {
    id: 'rm-cse-lab-1',
    name: 'AI & Cloud Computing Lab',
    roomNumber: 'CSE-G01',
    buildingId: 'bld-cse',
    floorNumber: 0,
    departmentId: 'dept-cse',
    type: 'lab',
    capacity: 80,
    headFaculty: 'Dr. N. Rajesh',
    nodeRefId: 'node-cse-lab1',
    tags: ['cse lab', 'ai lab', 'cloud lab', 'machine learning'],
    aliases: ['cse lab', 'cse lab 1', 'ai lab', 'cloud computing lab', 'computer lab 1', 'cse lab-ku epdi poganum'],
  },
  {
    id: 'rm-cse-lab-2',
    name: 'Software Systems Suite & Dev Lab',
    roomNumber: 'CSE-G02',
    buildingId: 'bld-cse',
    floorNumber: 0,
    departmentId: 'dept-cse',
    type: 'lab',
    capacity: 75,
    headFaculty: 'Prof. K. Vignesh',
    nodeRefId: 'node-cse-lab2',
    tags: ['cse lab 2', 'software lab', 'web lab', 'coding'],
    aliases: ['cse lab 2', 'software lab', 'dev lab', 'coding lab'],
  },
  {
    id: 'rm-cse-dept-office',
    name: 'CSE Department Office & HOD Cabin',
    roomNumber: 'CSE-101',
    buildingId: 'bld-cse',
    floorNumber: 1,
    departmentId: 'dept-cse',
    type: 'office',
    headFaculty: 'Dr. R. Meenakshi (HOD)',
    nodeRefId: 'node-cse-dept-office',
    tags: ['cse hod', 'cse office', 'staff room'],
    aliases: ['cse dept office', 'cse hod room', 'cse department', 'computer science office'],
  },
  {
    id: 'rm-cse-datahub',
    name: 'Robotics & Data Intelligence Hub',
    roomNumber: 'CSE-102',
    buildingId: 'bld-cse',
    floorNumber: 1,
    departmentId: 'dept-cse',
    type: 'lab',
    capacity: 50,
    headFaculty: 'Dr. S. Karthi',
    nodeRefId: 'node-cse-datahub',
    tags: ['robotics', 'data science', 'intelligence hub'],
    aliases: ['robotics lab', 'data hub', 'cse robotics', 'data intelligence'],
  },

  // Mechanical Block
  {
    id: 'rm-mech-lab',
    name: 'CAD/CAM Simulation & Robotics Lab',
    roomNumber: 'MECH-G01',
    buildingId: 'bld-mech',
    floorNumber: 0,
    departmentId: 'dept-mech',
    type: 'lab',
    capacity: 50,
    headFaculty: 'Dr. A. Balaji',
    nodeRefId: 'node-mech-lab',
    tags: ['cad cam', 'mechanical lab', 'robotics'],
    aliases: ['mech lab', 'mechanical lab', 'cad cam lab', 'machine shop'],
  },
  {
    id: 'rm-mech-dept-office',
    name: 'Mechanical Engineering Department Office',
    roomNumber: 'MECH-101',
    buildingId: 'bld-mech',
    floorNumber: 1,
    departmentId: 'dept-mech',
    type: 'office',
    headFaculty: 'Prof. J. Suresh',
    nodeRefId: 'node-mech-dept-office',
    tags: ['mech hod', 'mech office'],
    aliases: ['mech dept office', 'mech hod room', 'mechanical hod'],
  },
  {
    id: 'rm-mech-design',
    name: 'Design Studio & Fluid Mechanics Lab',
    roomNumber: 'MECH-102',
    buildingId: 'bld-mech',
    floorNumber: 1,
    departmentId: 'dept-mech',
    type: 'lab',
    capacity: 45,
    headFaculty: 'Dr. M. Pradeep',
    nodeRefId: 'node-mech-design',
    tags: ['design studio', 'fluids', 'thermo'],
    aliases: ['design studio', 'fluid lab', 'mech design studio'],
  },

  // Library
  {
    id: 'rm-library-ground',
    name: 'Central Library (Lending & Reading Section)',
    roomNumber: 'LIB-G01',
    buildingId: 'bld-library',
    floorNumber: 0,
    type: 'library',
    capacity: 300,
    headFaculty: 'Chief Librarian',
    nodeRefId: 'node-lib-ground',
    tags: ['library', 'books', 'reading', 'circulation'],
    aliases: ['library', 'central library', 'reading room', 'book lending', 'noolagam', 'library-ku route sollu', 'library enga'],
  },
  {
    id: 'rm-library-reading',
    name: 'General Reading & Study Cubicles',
    roomNumber: 'LIB-G02',
    buildingId: 'bld-library',
    floorNumber: 0,
    type: 'library',
    capacity: 150,
    headFaculty: 'Assistant Librarian',
    nodeRefId: 'node-lib-reading',
    tags: ['reading hall', 'study', 'cubicles'],
    aliases: ['reading hall', 'study room', 'quiet area'],
  },
  {
    id: 'rm-library-digital',
    name: 'Digital Knowledge Center & E-Resource Hub',
    roomNumber: 'LIB-101',
    buildingId: 'bld-library',
    floorNumber: 1,
    type: 'library',
    capacity: 100,
    headFaculty: 'Librarian (Digital Systems)',
    nodeRefId: 'node-lib-first',
    tags: ['digital library', 'computers', 'e-journals', 'research'],
    aliases: ['digital library', 'e library', 'research section', 'internet browsing lab'],
  },
  {
    id: 'rm-library-research',
    name: 'IEEE Journals & Research Archive',
    roomNumber: 'LIB-102',
    buildingId: 'bld-library',
    floorNumber: 1,
    type: 'library',
    capacity: 60,
    headFaculty: 'Research Coordinator',
    nodeRefId: 'node-lib-research',
    tags: ['ieee', 'journals', 'research archive'],
    aliases: ['ieee room', 'journal archive', 'research room'],
  },

  // Auditorium
  {
    id: 'rm-auditorium',
    name: 'Grand Campus Auditorium',
    roomNumber: 'AUD-MAIN',
    buildingId: 'bld-auditorium',
    floorNumber: 0,
    type: 'hall',
    capacity: 1200,
    headFaculty: 'Campus Event Bureau',
    nodeRefId: 'node-aud-hall',
    tags: ['auditorium', 'cultural', 'events', 'convocation'],
    aliases: ['auditorium', 'main audi', 'audi', 'kalaiyarangam', 'auditorium enga irukku'],
  },

  // Canteen
  {
    id: 'rm-canteen',
    name: 'College Food Court & Canteen',
    roomNumber: 'CAN-MAIN',
    buildingId: 'bld-canteen',
    floorNumber: 0,
    type: 'canteen',
    capacity: 400,
    nodeRefId: 'node-canteen-hall',
    tags: ['canteen', 'food', 'cafeteria', 'lunch', 'tea', 'snacks'],
    aliases: ['canteen', 'food court', 'cafeteria', 'mess', 'hotel', 'saapadu', 'tea kadai', 'canteen enga'],
  },
  {
    id: 'rm-canteen-bakery',
    name: 'Juice, Coffee & Bakery Kiosk',
    roomNumber: 'CAN-G02',
    buildingId: 'bld-canteen',
    floorNumber: 0,
    type: 'canteen',
    capacity: 50,
    nodeRefId: 'node-canteen-bakery',
    tags: ['bakery', 'juice', 'coffee', 'snacks'],
    aliases: ['juice shop', 'bakery', 'coffee shop', 'snacks counter'],
  },

  // Hostel
  {
    id: 'rm-hostel',
    name: 'Student Hostels & Residential Block',
    roomNumber: 'HST-BLOCK',
    buildingId: 'bld-hostel',
    floorNumber: 0,
    type: 'facility',
    capacity: 800,
    nodeRefId: 'node-hostel-office',
    tags: ['hostel', 'dorm', 'warden', 'rooms'],
    aliases: ['hostel', 'mens hostel', 'womens hostel', 'hostel block', 'viduthi', 'hostel enga'],
  },
  // Health Center Rooms
  {
    id: 'rm-health-clinic',
    name: 'Emergency Medical Clinic & Ward',
    roomNumber: 'HEALTH-G01',
    buildingId: 'bld-amenities',
    floorNumber: 0,
    type: 'medical',
    capacity: 20,
    nodeRefId: 'node-health-room',
    tags: ['medical', 'clinic', 'hospital', 'doctor', 'first aid', 'emergency'],
    aliases: ['clinic', 'medical room', 'doctor room', 'hospital', 'maruthuvamanai', 'ambulance'],
  },
  {
    id: 'rm-health-pharmacy',
    name: 'Campus Pharmacy & Dispensary',
    roomNumber: 'HEALTH-G02',
    buildingId: 'bld-amenities',
    floorNumber: 0,
    type: 'medical',
    capacity: 10,
    nodeRefId: 'node-health-pharmacy',
    tags: ['pharmacy', 'medicine', 'dispensary', 'tablets'],
    aliases: ['pharmacy', 'medical shop', 'dispensary', 'marunthu kadai'],
  },
];

export const INITIAL_FACILITIES: Facility[] = [
  {
    id: 'fac-health',
    name: 'Campus Medical Room & Emergency Aid',
    type: 'medical',
    buildingId: 'bld-amenities',
    floorNumber: 0,
    description: 'Physician on duty, basic trauma care, oxygen supply, and ambulance coordination',
    openHours: '24 Hours Open',
    emergency: true,
    nodeRefId: 'node-health-room',
    contactNumber: '+91 94440 12345 / Ext. 911',
  },
  {
    id: 'fac-canteen',
    name: 'College Main Canteen & Bakery',
    type: 'canteen',
    buildingId: 'bld-canteen',
    floorNumber: 0,
    description: 'Hot breakfast, South & North Indian meals, juices, and snacks',
    openHours: '7:30 AM - 8:00 PM',
    emergency: false,
    nodeRefId: 'node-canteen-hall',
  },
  {
    id: 'fac-restroom-admin',
    name: 'Accessible Restrooms (Admin Block)',
    type: 'restroom',
    buildingId: 'bld-admin',
    floorNumber: 0,
    description: 'Wheelchair accessible male & female restrooms with touchless fixtures',
    openHours: 'Open during campus hours',
    emergency: false,
    nodeRefId: 'node-admin-restroom',
  },
  {
    id: 'fac-restroom-ece',
    name: 'Restrooms & Washrooms (ECE Block)',
    type: 'restroom',
    buildingId: 'bld-ece',
    floorNumber: 0,
    description: 'Student & faculty washrooms with hand wash stations',
    openHours: 'Open during campus hours',
    emergency: false,
    nodeRefId: 'node-ece-restroom',
  },
  {
    id: 'fac-parking-main',
    name: 'Main Student & Staff Vehicle Parking',
    type: 'parking',
    floorNumber: 0,
    description: 'Two-wheeler and four-wheeler designated parking lots with security barrier',
    openHours: '6:00 AM - 9:30 PM',
    emergency: false,
    nodeRefId: 'node-parking',
  },
  {
    id: 'fac-atm',
    name: '24/7 Nationalized Bank ATM',
    type: 'atm',
    floorNumber: 0,
    description: 'All-bank debit/credit card ATM kiosk located beside Main Gate',
    openHours: '24/7',
    emergency: false,
    nodeRefId: 'node-atm',
  },
];

export const INITIAL_NODES: CampusNode[] = [
  // Outdoor / Gate & South Campus nodes
  { id: 'node-main-gate', name: 'Main Campus Gate & Security', floor: 0, x: 500, y: 770, type: 'gate', qrCode: 'CAMPUS_NODE_MAIN_GATE' },
  { id: 'node-atm', name: 'Campus Bank ATM (24/7)', floor: 0, x: 370, y: 770, type: 'landmark', qrCode: 'CAMPUS_NODE_ATM' },
  { id: 'node-parking', name: 'Vehicle Parking Complex', floor: 0, x: 230, y: 765, type: 'parking', qrCode: 'CAMPUS_NODE_PARKING' },
  { id: 'node-south-junction', name: 'South Avenue Plaza', floor: 0, x: 500, y: 700, type: 'landmark', qrCode: 'CAMPUS_NODE_SOUTH_PLAZA' },
  { id: 'node-admin-south-ent', name: 'Admin South Porch', buildingId: 'bld-admin', floor: 0, x: 500, y: 670, type: 'entrance', qrCode: 'CAMPUS_NODE_ADMIN_SOUTH' },

  // Admin Block Nodes (Ground Floor)
  { id: 'node-admin-ent', name: 'Administrative North Entrance', buildingId: 'bld-admin', floor: 0, x: 500, y: 530, type: 'entrance', qrCode: 'CAMPUS_NODE_ADMIN_ENTRANCE' },
  { id: 'node-admin-lobby', name: 'Admin Reception & Central Foyer', buildingId: 'bld-admin', floor: 0, x: 500, y: 600, type: 'corridor', qrCode: 'CAMPUS_NODE_ADMIN_LOBBY' },
  { id: 'node-admin-principal', name: 'Principal Office (ADM-G01)', buildingId: 'bld-admin', floor: 0, x: 420, y: 570, type: 'room', qrCode: 'CAMPUS_NODE_PRINCIPAL_OFFICE' },
  { id: 'node-admin-exam', name: 'Controller of Exams Cell (ADM-G02)', buildingId: 'bld-admin', floor: 0, x: 580, y: 570, type: 'room', qrCode: 'CAMPUS_NODE_EXAM_CELL' },
  { id: 'node-admin-accounts', name: 'Accounts & Fees Counter (ADM-G03)', buildingId: 'bld-admin', floor: 0, x: 420, y: 630, type: 'room', qrCode: 'CAMPUS_NODE_ACCOUNTS' },
  { id: 'node-admin-restroom', name: 'Admin Restroom (Accessible)', buildingId: 'bld-admin', floor: 0, x: 580, y: 630, type: 'room', qrCode: 'CAMPUS_NODE_ADMIN_RESTROOM' },
  { id: 'node-admin-stairs-g', name: 'Admin Block Stairs (Ground)', buildingId: 'bld-admin', floor: 0, x: 475, y: 600, type: 'stairs', qrCode: 'CAMPUS_NODE_ADMIN_STAIRS_G' },
  { id: 'node-admin-lift-g', name: 'Admin Accessible Elevator (Ground)', buildingId: 'bld-admin', floor: 0, x: 525, y: 600, type: 'lift', qrCode: 'CAMPUS_NODE_ADMIN_LIFT_G' },

  // Admin Block Nodes (First Floor)
  { id: 'node-admin-stairs-1', name: 'Admin Block Stairs (1st Floor)', buildingId: 'bld-admin', floor: 1, x: 475, y: 600, type: 'stairs', qrCode: 'CAMPUS_NODE_ADMIN_STAIRS_1' },
  { id: 'node-admin-lift-1', name: 'Admin Accessible Elevator (1st Floor)', buildingId: 'bld-admin', floor: 1, x: 525, y: 600, type: 'lift', qrCode: 'CAMPUS_NODE_ADMIN_LIFT_1' },
  { id: 'node-admin-corridor-1', name: 'Admin 1st Floor Gallery Corridor', buildingId: 'bld-admin', floor: 1, x: 500, y: 600, type: 'corridor', qrCode: 'CAMPUS_NODE_ADMIN_CORRIDOR_1' },
  { id: 'node-admin-boardroom', name: 'Executive Board Room (ADM-101)', buildingId: 'bld-admin', floor: 1, x: 420, y: 570, type: 'room', qrCode: 'CAMPUS_NODE_BOARD_ROOM' },
  { id: 'node-admin-dean', name: 'Academic Dean Office (ADM-102)', buildingId: 'bld-admin', floor: 1, x: 580, y: 570, type: 'room', qrCode: 'CAMPUS_NODE_DEAN_OFFICE' },

  // Central Walkway & Junction Network
  { id: 'node-central-junction', name: 'Central Campus Quadrangle', floor: 0, x: 500, y: 440, type: 'landmark', qrCode: 'CAMPUS_NODE_CENTRAL_QUAD' },
  { id: 'node-junction-west', name: 'West Promenade (ECE & Mech Avenue)', floor: 0, x: 230, y: 440, type: 'landmark', qrCode: 'CAMPUS_NODE_JUNCTION_WEST' },
  { id: 'node-junction-east', name: 'East Promenade (CSE & Audi Avenue)', floor: 0, x: 770, y: 440, type: 'landmark', qrCode: 'CAMPUS_NODE_JUNCTION_EAST' },
  { id: 'node-junction-north', name: 'North Boulevard (Library & Health Center)', floor: 0, x: 500, y: 220, type: 'landmark', qrCode: 'CAMPUS_NODE_JUNCTION_NORTH' },
  { id: 'node-junction-north-west', name: 'North-West Pathway (Canteen & Mech)', floor: 0, x: 230, y: 220, type: 'landmark', qrCode: 'CAMPUS_NODE_JUNCTION_NW' },
  { id: 'node-junction-north-east', name: 'North-East Pathway (Hostels & Audi)', floor: 0, x: 770, y: 220, type: 'landmark', qrCode: 'CAMPUS_NODE_JUNCTION_NE' },

  // ECE Block Nodes (Ground Floor)
  { id: 'node-ece-ent', name: 'ECE Block North Entrance & Ramp', buildingId: 'bld-ece', floor: 0, x: 230, y: 450, type: 'entrance', qrCode: 'CAMPUS_NODE_ECE_ENTRANCE' },
  { id: 'node-ece-lobby-g', name: 'ECE Ground Lobby & Foyer', buildingId: 'bld-ece', floor: 0, x: 230, y: 510, type: 'corridor', qrCode: 'CAMPUS_NODE_ECE_LOBBY_G' },
  { id: 'node-ece-lab1', name: 'ECE Lab 1 - VLSI & DSP (ECE-G01)', buildingId: 'bld-ece', floor: 0, x: 170, y: 500, type: 'room', qrCode: 'CAMPUS_NODE_ECE_LAB1' },
  { id: 'node-ece-lab2', name: 'ECE Lab 2 - Embedded & IoT (ECE-G02)', buildingId: 'bld-ece', floor: 0, x: 170, y: 550, type: 'room', qrCode: 'CAMPUS_NODE_ECE_LAB2' },
  { id: 'node-ece-restroom', name: 'ECE Ground Washrooms', buildingId: 'bld-ece', floor: 0, x: 290, y: 550, type: 'room', qrCode: 'CAMPUS_NODE_ECE_RESTROOM' },
  { id: 'node-ece-stairs-g', name: 'ECE West Stairs (Ground)', buildingId: 'bld-ece', floor: 0, x: 220, y: 540, type: 'stairs', qrCode: 'CAMPUS_NODE_ECE_STAIRS_G' },
  { id: 'node-ece-lift-g', name: 'ECE Accessible Elevator (Ground)', buildingId: 'bld-ece', floor: 0, x: 250, y: 540, type: 'lift', qrCode: 'CAMPUS_NODE_ECE_LIFT_G' },

  // ECE Block Nodes (First Floor)
  { id: 'node-ece-stairs-1', name: 'ECE West Stairs (1st Floor)', buildingId: 'bld-ece', floor: 1, x: 220, y: 540, type: 'stairs', qrCode: 'CAMPUS_NODE_ECE_STAIRS_1' },
  { id: 'node-ece-lift-1', name: 'ECE Accessible Elevator (1st Floor)', buildingId: 'bld-ece', floor: 1, x: 250, y: 540, type: 'lift', qrCode: 'CAMPUS_NODE_ECE_LIFT_1' },
  { id: 'node-ece-corridor-1', name: 'ECE 1st Floor Gallery Corridor', buildingId: 'bld-ece', floor: 1, x: 230, y: 510, type: 'corridor', qrCode: 'CAMPUS_NODE_ECE_CORRIDOR_1' },
  { id: 'node-ece-dept-office', name: 'ECE Department Office & HOD (ECE-101)', buildingId: 'bld-ece', floor: 1, x: 170, y: 500, type: 'room', qrCode: 'CAMPUS_NODE_ECE_HOD' },
  { id: 'node-ece-seminar', name: 'College Seminar Hall (ECE-102)', buildingId: 'bld-ece', floor: 1, x: 170, y: 550, type: 'hall', qrCode: 'CAMPUS_NODE_SEMINAR_HALL' },

  // CSE Block Nodes (Ground Floor)
  { id: 'node-cse-ent', name: 'CSE Block North Entrance', buildingId: 'bld-cse', floor: 0, x: 770, y: 450, type: 'entrance', qrCode: 'CAMPUS_NODE_CSE_ENTRANCE' },
  { id: 'node-cse-lobby-g', name: 'CSE Ground Floor Foyer', buildingId: 'bld-cse', floor: 0, x: 770, y: 510, type: 'corridor', qrCode: 'CAMPUS_NODE_CSE_LOBBY_G' },
  { id: 'node-cse-lab1', name: 'AI & Cloud Computing Lab (CSE-G01)', buildingId: 'bld-cse', floor: 0, x: 830, y: 500, type: 'room', qrCode: 'CAMPUS_NODE_CSE_LAB1' },
  { id: 'node-cse-lab2', name: 'Software Systems Suite (CSE-G02)', buildingId: 'bld-cse', floor: 0, x: 830, y: 550, type: 'room', qrCode: 'CAMPUS_NODE_CSE_LAB2' },
  { id: 'node-cse-lift-g', name: 'CSE Accessible Elevator (Ground)', buildingId: 'bld-cse', floor: 0, x: 730, y: 540, type: 'lift', qrCode: 'CAMPUS_NODE_CSE_LIFT_G' },
  { id: 'node-cse-stairs-g', name: 'CSE Block Stairs (Ground)', buildingId: 'bld-cse', floor: 0, x: 760, y: 540, type: 'stairs', qrCode: 'CAMPUS_NODE_CSE_STAIRS_G' },

  // CSE Block Nodes (First Floor)
  { id: 'node-cse-lift-1', name: 'CSE Accessible Elevator (1st Floor)', buildingId: 'bld-cse', floor: 1, x: 730, y: 540, type: 'lift', qrCode: 'CAMPUS_NODE_CSE_LIFT_1' },
  { id: 'node-cse-stairs-1', name: 'CSE Block Stairs (1st Floor)', buildingId: 'bld-cse', floor: 1, x: 760, y: 540, type: 'stairs', qrCode: 'CAMPUS_NODE_CSE_STAIRS_1' },
  { id: 'node-cse-corridor-1', name: 'CSE 1st Floor Gallery Corridor', buildingId: 'bld-cse', floor: 1, x: 770, y: 510, type: 'corridor', qrCode: 'CAMPUS_NODE_CSE_CORRIDOR_1' },
  { id: 'node-cse-dept-office', name: 'CSE Department Office & HOD (CSE-101)', buildingId: 'bld-cse', floor: 1, x: 830, y: 500, type: 'room', qrCode: 'CAMPUS_NODE_CSE_HOD' },
  { id: 'node-cse-datahub', name: 'Robotics & Data Intelligence Hub (CSE-102)', buildingId: 'bld-cse', floor: 1, x: 830, y: 550, type: 'room', qrCode: 'CAMPUS_NODE_CSE_DATAHUB' },

  // Central Library Nodes
  { id: 'node-lib-ent', name: 'Central Library Main Entrance', buildingId: 'bld-library', floor: 0, x: 500, y: 400, type: 'entrance', qrCode: 'CAMPUS_NODE_LIB_ENTRANCE' },
  { id: 'node-lib-ground', name: 'Library Lending & Book Stacks (LIB-G01)', buildingId: 'bld-library', floor: 0, x: 450, y: 335, type: 'room', qrCode: 'CAMPUS_NODE_LIB_GROUND' },
  { id: 'node-lib-reading', name: 'General Reading & Study Hall (LIB-G02)', buildingId: 'bld-library', floor: 0, x: 550, y: 335, type: 'room', qrCode: 'CAMPUS_NODE_LIB_READING' },
  { id: 'node-lib-lift', name: 'Library Accessible Elevator (Ground)', buildingId: 'bld-library', floor: 0, x: 500, y: 320, type: 'lift', qrCode: 'CAMPUS_NODE_LIB_LIFT' },
  { id: 'node-lib-stairs-g', name: 'Library Central Staircase (Ground)', buildingId: 'bld-library', floor: 0, x: 500, y: 360, type: 'stairs', qrCode: 'CAMPUS_NODE_LIB_STAIRS_G' },
  { id: 'node-lib-lift-1', name: 'Library Accessible Elevator (1st Floor)', buildingId: 'bld-library', floor: 1, x: 500, y: 320, type: 'lift', qrCode: 'CAMPUS_NODE_LIB_LIFT_1' },
  { id: 'node-lib-stairs-1', name: 'Library Central Staircase (1st Floor)', buildingId: 'bld-library', floor: 1, x: 500, y: 360, type: 'stairs', qrCode: 'CAMPUS_NODE_LIB_STAIRS_1' },
  { id: 'node-lib-first', name: 'Digital Knowledge & E-Library (LIB-101)', buildingId: 'bld-library', floor: 1, x: 450, y: 335, type: 'room', qrCode: 'CAMPUS_NODE_LIB_FIRST' },
  { id: 'node-lib-research', name: 'IEEE Journals & Research Archive (LIB-102)', buildingId: 'bld-library', floor: 1, x: 550, y: 335, type: 'room', qrCode: 'CAMPUS_NODE_LIB_RESEARCH' },

  // Mechanical Block Nodes
  { id: 'node-mech-ent', name: 'Mechanical Block Entrance Porch', buildingId: 'bld-mech', floor: 0, x: 230, y: 395, type: 'entrance', qrCode: 'CAMPUS_NODE_MECH_ENTRANCE' },
  { id: 'node-mech-lobby', name: 'Mech Ground Floor Hallway', buildingId: 'bld-mech', floor: 0, x: 230, y: 330, type: 'corridor', qrCode: 'CAMPUS_NODE_MECH_LOBBY' },
  { id: 'node-mech-lab', name: 'CAD/CAM Simulation & Robotics (MECH-G01)', buildingId: 'bld-mech', floor: 0, x: 170, y: 330, type: 'room', qrCode: 'CAMPUS_NODE_MECH_LAB' },
  { id: 'node-mech-stairs-g', name: 'Mech Main Stairs (Ground)', buildingId: 'bld-mech', floor: 0, x: 230, y: 360, type: 'stairs', qrCode: 'CAMPUS_NODE_MECH_STAIRS_G' },
  { id: 'node-mech-stairs-1', name: 'Mech Main Stairs (1st Floor)', buildingId: 'bld-mech', floor: 1, x: 230, y: 360, type: 'stairs', qrCode: 'CAMPUS_NODE_MECH_STAIRS_1' },
  { id: 'node-mech-dept-office', name: 'Mechanical Department Office & HOD (MECH-101)', buildingId: 'bld-mech', floor: 1, x: 170, y: 330, type: 'room', qrCode: 'CAMPUS_NODE_MECH_HOD' },
  { id: 'node-mech-design', name: 'Design Studio & Fluid Mechanics (MECH-102)', buildingId: 'bld-mech', floor: 1, x: 280, y: 330, type: 'room', qrCode: 'CAMPUS_NODE_MECH_DESIGN' },

  // Auditorium Nodes
  { id: 'node-aud-ent', name: 'Grand Auditorium Entrance Portico', buildingId: 'bld-auditorium', floor: 0, x: 770, y: 395, type: 'entrance', qrCode: 'CAMPUS_NODE_AUD_ENTRANCE' },
  { id: 'node-aud-hall', name: 'Main Auditorium Seating & Stage', buildingId: 'bld-auditorium', floor: 0, x: 770, y: 320, type: 'room', qrCode: 'CAMPUS_NODE_AUD_HALL' },

  // Canteen Nodes
  { id: 'node-canteen-ent', name: 'Food Court & Canteen Entrance', buildingId: 'bld-canteen', floor: 0, x: 230, y: 190, type: 'entrance', qrCode: 'CAMPUS_NODE_CANTEEN_ENTRANCE' },
  { id: 'node-canteen-hall', name: 'Dining Hall & Multi-Cuisine Counters', buildingId: 'bld-canteen', floor: 0, x: 190, y: 130, type: 'room', qrCode: 'CAMPUS_NODE_CANTEEN_HALL' },
  { id: 'node-canteen-bakery', name: 'Juice, Coffee & Bakery Kiosk', buildingId: 'bld-canteen', floor: 0, x: 270, y: 130, type: 'room', qrCode: 'CAMPUS_NODE_CANTEEN_BAKERY' },

  // Health Center Nodes
  { id: 'node-health-ent', name: 'Health Center Ambulance Porch', buildingId: 'bld-amenities', floor: 0, x: 500, y: 190, type: 'entrance', qrCode: 'CAMPUS_NODE_HEALTH_ENTRANCE' },
  { id: 'node-health-room', name: 'Emergency Clinic & Physician Ward', buildingId: 'bld-amenities', floor: 0, x: 450, y: 130, type: 'room', qrCode: 'CAMPUS_NODE_HEALTH_ROOM' },
  { id: 'node-health-pharmacy', name: 'Campus Pharmacy & Dispensary', buildingId: 'bld-amenities', floor: 0, x: 550, y: 130, type: 'room', qrCode: 'CAMPUS_NODE_HEALTH_PHARMACY' },

  // Hostels
  { id: 'node-hostel-ent', name: 'Hostel Complex Security Entrance', buildingId: 'bld-hostel', floor: 0, x: 770, y: 190, type: 'entrance', qrCode: 'CAMPUS_NODE_HOSTEL_ENTRANCE' },
  { id: 'node-hostel-office', name: 'Hostel Office & Chief Warden', buildingId: 'bld-hostel', floor: 0, x: 770, y: 130, type: 'room', qrCode: 'CAMPUS_NODE_HOSTEL_OFFICE' },
];

export const INITIAL_EDGES: CampusEdge[] = [
  // Outdoor South Avenue & Main Gate Spine
  { id: 'e-gate-south', fromNode: 'node-main-gate', toNode: 'node-south-junction', distance: 70, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-gate-atm', fromNode: 'node-main-gate', toNode: 'node-atm', distance: 30, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-atm-parking', fromNode: 'node-atm', toNode: 'node-parking', distance: 45, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-parking-south', fromNode: 'node-parking', toNode: 'node-south-junction', distance: 80, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-south-admin-south', fromNode: 'node-south-junction', toNode: 'node-admin-south-ent', distance: 30, accessible: true, type: 'outdoor_path', bidirectional: true },

  // Admin Block Outer Walkway Bypass (allows walking around Admin to Quad)
  { id: 'e-south-west-promenade', fromNode: 'node-south-junction', toNode: 'node-junction-west', distance: 130, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-south-east-promenade', fromNode: 'node-south-junction', toNode: 'node-junction-east', distance: 130, accessible: true, type: 'outdoor_path', bidirectional: true },

  // Admin Block Interior (Ground Floor)
  { id: 'e-admin-south-lobby', fromNode: 'node-admin-south-ent', toNode: 'node-admin-lobby', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-admin-north-lobby', fromNode: 'node-admin-ent', toNode: 'node-admin-lobby', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-admin-lobby-principal', fromNode: 'node-admin-lobby', toNode: 'node-admin-principal', distance: 25, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-admin-lobby-exam', fromNode: 'node-admin-lobby', toNode: 'node-admin-exam', distance: 25, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-admin-lobby-accounts', fromNode: 'node-admin-lobby', toNode: 'node-admin-accounts', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-admin-lobby-restroom', fromNode: 'node-admin-lobby', toNode: 'node-admin-restroom', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-admin-lobby-stairs-g', fromNode: 'node-admin-lobby', toNode: 'node-admin-stairs-g', distance: 12, accessible: false, type: 'corridor', bidirectional: true },
  { id: 'e-admin-lobby-lift-g', fromNode: 'node-admin-lobby', toNode: 'node-admin-lift-g', distance: 12, accessible: true, type: 'corridor', bidirectional: true },

  // Admin Vertical Links (Ground to 1st Floor)
  { id: 'e-admin-stairs-vert', fromNode: 'node-admin-stairs-g', toNode: 'node-admin-stairs-1', distance: 18, accessible: false, type: 'stairs', bidirectional: true },
  { id: 'e-admin-lift-vert', fromNode: 'node-admin-lift-g', toNode: 'node-admin-lift-1', distance: 12, accessible: true, type: 'lift', bidirectional: true },

  // Admin Interior (1st Floor)
  { id: 'e-admin-stairs1-corr', fromNode: 'node-admin-stairs-1', toNode: 'node-admin-corridor-1', distance: 10, accessible: false, type: 'corridor', bidirectional: true },
  { id: 'e-admin-lift1-corr', fromNode: 'node-admin-lift-1', toNode: 'node-admin-corridor-1', distance: 10, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-admin-corr-boardroom', fromNode: 'node-admin-corridor-1', toNode: 'node-admin-boardroom', distance: 25, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-admin-corr-dean', fromNode: 'node-admin-corridor-1', toNode: 'node-admin-dean', distance: 25, accessible: true, type: 'corridor', bidirectional: true },

  // Central Quadrangle to Admin North
  { id: 'e-quad-admin-ent', fromNode: 'node-central-junction', toNode: 'node-admin-ent', distance: 45, accessible: true, type: 'outdoor_path', bidirectional: true },

  // Central Quadrangle Promenade Network
  { id: 'e-quad-west', fromNode: 'node-central-junction', toNode: 'node-junction-west', distance: 80, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-quad-east', fromNode: 'node-central-junction', toNode: 'node-junction-east', distance: 80, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-quad-north', fromNode: 'node-central-junction', toNode: 'node-junction-north', distance: 120, accessible: true, type: 'outdoor_path', bidirectional: true },

  // West Promenade -> ECE Block
  { id: 'e-west-ece-ent', fromNode: 'node-junction-west', toNode: 'node-ece-ent', distance: 15, accessible: true, type: 'ramp', bidirectional: true },
  { id: 'e-ece-ent-lobby', fromNode: 'node-ece-ent', toNode: 'node-ece-lobby-g', distance: 18, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-ece-lobby-lab1', fromNode: 'node-ece-lobby-g', toNode: 'node-ece-lab1', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-ece-lobby-lab2', fromNode: 'node-ece-lobby-g', toNode: 'node-ece-lab2', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-ece-lobby-restroom', fromNode: 'node-ece-lobby-g', toNode: 'node-ece-restroom', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-ece-lobby-stairs-g', fromNode: 'node-ece-lobby-g', toNode: 'node-ece-stairs-g', distance: 12, accessible: false, type: 'corridor', bidirectional: true },
  { id: 'e-ece-lobby-lift-g', fromNode: 'node-ece-lobby-g', toNode: 'node-ece-lift-g', distance: 12, accessible: true, type: 'corridor', bidirectional: true },

  // ECE Vertical Links
  { id: 'e-ece-stairs-vert', fromNode: 'node-ece-stairs-g', toNode: 'node-ece-stairs-1', distance: 18, accessible: false, type: 'stairs', bidirectional: true },
  { id: 'e-ece-lift-vert', fromNode: 'node-ece-lift-g', toNode: 'node-ece-lift-1', distance: 12, accessible: true, type: 'lift', bidirectional: true },

  // ECE First Floor
  { id: 'e-ece-stairs1-corr', fromNode: 'node-ece-stairs-1', toNode: 'node-ece-corridor-1', distance: 10, accessible: false, type: 'corridor', bidirectional: true },
  { id: 'e-ece-lift1-corr', fromNode: 'node-ece-lift-1', toNode: 'node-ece-corridor-1', distance: 10, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-ece-corr-hod', fromNode: 'node-ece-corridor-1', toNode: 'node-ece-dept-office', distance: 25, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-ece-corr-seminar', fromNode: 'node-ece-corridor-1', toNode: 'node-ece-seminar', distance: 25, accessible: true, type: 'corridor', bidirectional: true },

  // West Promenade -> Mech Block
  { id: 'e-west-mech-ent', fromNode: 'node-junction-west', toNode: 'node-mech-ent', distance: 35, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-mech-ent-lobby', fromNode: 'node-mech-ent', toNode: 'node-mech-lobby', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-mech-lobby-lab', fromNode: 'node-mech-lobby', toNode: 'node-mech-lab', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-mech-lobby-stairs-g', fromNode: 'node-mech-lobby', toNode: 'node-mech-stairs-g', distance: 12, accessible: false, type: 'corridor', bidirectional: true },
  { id: 'e-mech-stairs-vert', fromNode: 'node-mech-stairs-g', toNode: 'node-mech-stairs-1', distance: 18, accessible: false, type: 'stairs', bidirectional: true },
  { id: 'e-mech-stairs1-hod', fromNode: 'node-mech-stairs-1', toNode: 'node-mech-dept-office', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-mech-stairs1-design', fromNode: 'node-mech-stairs-1', toNode: 'node-mech-design', distance: 20, accessible: true, type: 'corridor', bidirectional: true },

  // East Promenade -> CSE Block
  { id: 'e-east-cse-ent', fromNode: 'node-junction-east', toNode: 'node-cse-ent', distance: 15, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-cse-ent-lobby', fromNode: 'node-cse-ent', toNode: 'node-cse-lobby-g', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-cse-lobby-lab1', fromNode: 'node-cse-lobby-g', toNode: 'node-cse-lab1', distance: 25, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-cse-lobby-lab2', fromNode: 'node-cse-lobby-g', toNode: 'node-cse-lab2', distance: 25, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-cse-lobby-lift-g', fromNode: 'node-cse-lobby-g', toNode: 'node-cse-lift-g', distance: 15, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-cse-lobby-stairs-g', fromNode: 'node-cse-lobby-g', toNode: 'node-cse-stairs-g', distance: 15, accessible: false, type: 'corridor', bidirectional: true },

  // CSE Vertical Links
  { id: 'e-cse-lift-vert', fromNode: 'node-cse-lift-g', toNode: 'node-cse-lift-1', distance: 12, accessible: true, type: 'lift', bidirectional: true },
  { id: 'e-cse-stairs-vert', fromNode: 'node-cse-stairs-g', toNode: 'node-cse-stairs-1', distance: 18, accessible: false, type: 'stairs', bidirectional: true },

  // CSE First Floor
  { id: 'e-cse-lift1-corr', fromNode: 'node-cse-lift-1', toNode: 'node-cse-corridor-1', distance: 10, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-cse-stairs1-corr', fromNode: 'node-cse-stairs-1', toNode: 'node-cse-corridor-1', distance: 10, accessible: false, type: 'corridor', bidirectional: true },
  { id: 'e-cse-corr-hod', fromNode: 'node-cse-corridor-1', toNode: 'node-cse-dept-office', distance: 25, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-cse-corr-datahub', fromNode: 'node-cse-corridor-1', toNode: 'node-cse-datahub', distance: 25, accessible: true, type: 'corridor', bidirectional: true },

  // East Promenade -> Auditorium
  { id: 'e-east-aud-ent', fromNode: 'node-junction-east', toNode: 'node-aud-ent', distance: 35, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-aud-ent-hall', fromNode: 'node-aud-ent', toNode: 'node-aud-hall', distance: 25, accessible: true, type: 'corridor', bidirectional: true },

  // Central Promenade to Library Entrance
  { id: 'e-quad-lib-ent', fromNode: 'node-central-junction', toNode: 'node-lib-ent', distance: 30, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-lib-ent-ground', fromNode: 'node-lib-ent', toNode: 'node-lib-ground', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-lib-ent-reading', fromNode: 'node-lib-ent', toNode: 'node-lib-reading', distance: 20, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-lib-ground-lift', fromNode: 'node-lib-ground', toNode: 'node-lib-lift', distance: 15, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-lib-ground-stairs', fromNode: 'node-lib-ground', toNode: 'node-lib-stairs-g', distance: 15, accessible: false, type: 'corridor', bidirectional: true },
  { id: 'e-lib-lift-vert', fromNode: 'node-lib-lift', toNode: 'node-lib-lift-1', distance: 12, accessible: true, type: 'lift', bidirectional: true },
  { id: 'e-lib-stairs-vert', fromNode: 'node-lib-stairs-g', toNode: 'node-lib-stairs-1', distance: 18, accessible: false, type: 'stairs', bidirectional: true },
  { id: 'e-lib-lift1-first', fromNode: 'node-lib-lift-1', toNode: 'node-lib-first', distance: 15, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-lib-first-research', fromNode: 'node-lib-first', toNode: 'node-lib-research', distance: 25, accessible: true, type: 'corridor', bidirectional: true },

  // North Avenue Links
  { id: 'e-north-nw', fromNode: 'node-junction-north', toNode: 'node-junction-north-west', distance: 80, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-north-ne', fromNode: 'node-junction-north', toNode: 'node-junction-north-east', distance: 80, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-nw-canteen', fromNode: 'node-junction-north-west', toNode: 'node-canteen-ent', distance: 20, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-canteen-hall', fromNode: 'node-canteen-ent', toNode: 'node-canteen-hall', distance: 18, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-canteen-bakery', fromNode: 'node-canteen-ent', toNode: 'node-canteen-bakery', distance: 18, accessible: true, type: 'corridor', bidirectional: true },

  { id: 'e-north-health', fromNode: 'node-junction-north', toNode: 'node-health-ent', distance: 20, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-health-room', fromNode: 'node-health-ent', toNode: 'node-health-room', distance: 18, accessible: true, type: 'corridor', bidirectional: true },
  { id: 'e-health-pharmacy', fromNode: 'node-health-ent', toNode: 'node-health-pharmacy', distance: 18, accessible: true, type: 'corridor', bidirectional: true },

  { id: 'e-ne-hostel', fromNode: 'node-junction-north-east', toNode: 'node-hostel-ent', distance: 20, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-hostel-office', fromNode: 'node-hostel-ent', toNode: 'node-hostel-office', distance: 20, accessible: true, type: 'corridor', bidirectional: true },

  // North-to-South cross walkways along the sides
  { id: 'e-mech-nw', fromNode: 'node-mech-ent', toNode: 'node-junction-north-west', distance: 60, accessible: true, type: 'outdoor_path', bidirectional: true },
  { id: 'e-audi-ne', fromNode: 'node-aud-ent', toNode: 'node-junction-north-east', distance: 60, accessible: true, type: 'outdoor_path', bidirectional: true },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Semester End Theory & Practical Examination Timetable Released',
    content: 'All students are advised to collect their hall tickets from the Exam Cell (ADM-G02). Strictly adhere to the reported seating order.',
    priority: 'urgent',
    department: 'Controller of Examinations',
    date: '2026-09-02',
    active: true,
    createdAt: '2026-09-02T08:00:00Z',
  },
  {
    id: 'ann-2',
    title: 'National Robotics & IoT Hackathon in Seminar Hall',
    content: 'Join the inter-collegiate symposium this Friday at 9:30 AM in College Seminar Hall (ECE-102). Keynote by industry mentors.',
    priority: 'event',
    department: 'ECE Department',
    date: '2026-09-03',
    active: true,
    createdAt: '2026-09-03T09:00:00Z',
  },
  {
    id: 'ann-3',
    title: 'Campus Free Health & Wellness Screening Camp',
    content: 'Free eye checkups and general medical consultations available today at Campus Health Center (Clinic Porch).',
    priority: 'normal',
    department: 'Health Services',
    date: '2026-09-03',
    active: true,
    createdAt: '2026-09-03T10:00:00Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    uid: 'usr-admin-1',
    name: 'Dr. V. Ramanathan',
    email: 'admin@college.edu',
    role: 'admin',
    department: 'Campus Administration',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    uid: 'usr-staff-1',
    name: 'Prof. T. Anand',
    email: 'staff@college.edu',
    role: 'staff',
    department: 'Electronics & Communication',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    uid: 'usr-student-1',
    name: 'Gokul K.',
    email: 'student@college.edu',
    role: 'student',
    department: 'Electronics & Communication',
    year: '3rd Year',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
];
